### ISSUE TITLE
Motion Prior for the Left Hand

### ISSUE THREAD

**Issue by zhangy76** [enesduran/HMP#1]
Hi,

Thank you for sharing the great work! May I ask how to handle left hand motion? Are we supposed to train the motion prior using left hand pose data?

Thanks,
Yufei

**Comment by enesduran** [comment]
Hey, glad to hear your words. 

It is not necessary to train on the left hand motion actually. What you can do is to flip the output of the motion prior model so that it becomes left hand.  For an axis angle output you can multiply with [1, -1, -1] to flip hands 

This trick allows us to leverage the left hand in the dataset in training actually. In data processing we flipped left hands to get more data.

**Comment by zhangy76** [comment]
Thank you for the prompt reply! Got it. So, we utilize both the left and right hand data to train the hand motion prior (we also have more data by doing this). During testing, the prior model can work for both cases by flipping the input when needed.

Yufei

**Comment by enesduran** [comment]
Exactly. Just flip the hand when encoding (if left) and then flip the output back.

**Comment by zhangy76** [comment]
Got it. Thanks.
